# Generated by Django 4.1.2 on 2022-10-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(max_length=200)),
                ('tipDocumento', models.CharField(max_length=200)),
                ('numeroDocumento', models.CharField(max_length=200)),
                ('nombreTurista', models.CharField(max_length=200)),
                ('procedencia', models.CharField(max_length=200)),
                ('acompañado', models.CharField(max_length=200)),
                ('tiempoEstadia', models.CharField(max_length=200)),
                ('transporte', models.CharField(max_length=200)),
                ('dinero', models.CharField(max_length=200)),
                ('equipaje', models.CharField(max_length=200)),
            ],
        ),
    ]
