# Generated by Django 4.1.2 on 2022-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_task_project_remove_turista_tiempoestadia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turista',
            name='fechaLlegada',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='turista',
            name='tipDocumento',
            field=models.IntegerField(choices=[[0, 'Cedula de ciudadania'], [1, 'Cedula Extranjera'], [2, 'Pasaporte']]),
        ),
    ]
