# Generated by Django 4.1.2 on 2022-10-25 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_turista_fechallegada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrarEstablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=200)),
                ('tipoEstablecimiento', models.CharField(max_length=200)),
                ('nombreEstablecimiento', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('propietario', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
