# Generated by Django 4.1.2 on 2022-10-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_registrarestablecimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrarestablecimiento',
            name='usuario',
        ),
    ]
