# Generated by Django 4.1.2 on 2022-10-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_registrarestablecimiento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turista',
            name='tipDocumento',
            field=models.CharField(max_length=200),
        ),
    ]
