# Generated by Django 3.2.18 on 2023-04-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_turista_tipdocumento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrarEstablecimiento',
        ),
        migrations.DeleteModel(
            name='Turista',
        ),
    ]
