# Generated by Django 3.2.18 on 2023-04-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_crearcurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombrePrograma', models.CharField(max_length=30)),
                ('duracion', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='crearcurso',
            name='id',
        ),
        migrations.AlterField(
            model_name='crearcurso',
            name='idCurso',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('Profesor', 'Profesor'), ('Alumno', 'Alumno')], default='Alumno', max_length=9)),
                ('apellidos', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=30)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('validacion', models.BooleanField(default=True)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMatricula', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usercourse')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.crearcurso')),
            ],
        ),
    ]
