# Generated by Django 3.2.18 on 2023-05-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
